# List of all sounds that can be eared by the player when he is verified by a staff.
# https://jd.andross.fr/1.12.2/org/bukkit/Sound.html
sounds:
  - BLOCK_ANVIL_PLACE
  - BLOCK_ANVIL_BREAK

# List of all message that can be sent to the player for the verification.
player-check-message:

# Message sent to the staff when he executes the /checkafk command.
staff-message: