name: CheckAFK
version: '${project.version}'
main: be.achent.checkafk.CheckAFK
load: STARTUP
softdepend: [PlaceHolderAPI]
author: 'Achent'
commands:
  checkafk:
    description: main command
permissions:
  checkafk.*:
    description: Give all permissions of the plugin
    children:
      checkafk.help: true
      checkafk.staff: true
      checkafk.reload: true
  checkafk.staff:
    description: Permission to give to the staff for allowing to execute the command
    default: op
  checkafk.help:
    description: Permission to see the help command
    default: op
  checkafk.reload:
    description: Permission to execute the /checkafk reload command
    default: op